name: "rust-check"
description: "Check rust project with formatting, clippy and test"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Cargo fmt 
      run: cargo fmt --check
      shell: bash

    - uses: Swatinem/rust-cache@v2

    - name: Cargo clippy
      run: cargo clippy -- -D warnings
      shell: bash

    - name: Cargo test
      run: cargo test --verbose
      shell: bash
