name: "rust-check"
description: "Check rust project with formatting, clippy and test"
inputs:
  build:
    description: "Optionally build"
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Show build parameter
      run: echo "Build is $BUILD"
      shell: bash
      env:
        BUILD: ${{ inputs.build }}

    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2

    - name: Cargo fmt
      run: cargo fmt --check
      shell: bash

    - name: Cargo clippy
      run: cargo clippy -- -D warnings
      shell: bash

    - name: Cargo test
      run: cargo test --verbose
      shell: bash

    - name: Cargo build
      run: cargo build --release
      shell: bash
      if: ${{ inputs.build }} == 'true'
